language: cpp

sudo: required

dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      env:
        - WX_CONFIG=debug
        - CONFIG=debug
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      env:
        - WX_CONFIG=release
        - CONFIG=intermediate
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      env:
        - WX_CONFIG=release
        - CONFIG=profile
    - os: osx
      osx_image: xcode7.2
      compiler: clang
      env:
        - WX_CONFIG=release
        - CONFIG=release
    - os: linux
      compiler: gcc
      env:
        - WX_CONFIG=debug
        - CONFIG=debug
    - os: linux
      compiler: gcc
      env:
        - WX_CONFIG=release
        - CONFIG=intermediate
    - os: linux
      compiler: gcc
      env:
        - WX_CONFIG=release
        - CONFIG=profile
    - os: linux
      compiler: gcc
      env:
        - WX_CONFIG=release
        - CONFIG=release

git:
  submodules: false

before_install:
- git submodule update --init --recursive
- ./.travis.before_install.$TRAVIS_OS_NAME.sh

script:
- cd Dependencies
- ../premake.sh --wx-config=${WX_CONFIG} gmake config=${CONFIG}_x64
- make -j4
- cd ..
- ./premake.sh gmake config=${CONFIG}_x64
- make -j4

notifications:
  slack:
    rooms:
      secure: nn6rH9yj4/eJYNkAXrMIk4oVrweT3rznA5ATtuHzFeeG5uMT0qr1c1yQqDsSKsxtPan1RFo2awJ/PZkGQmuRVTcmVuaHs0eLPVrTXgfy2yjjuqwg4aLlK7PBEnv6oxUDyJOo9K9RYMcPIqXu0vcikgo+C4Oc6qL5MiOa7RleVjI=
    on_start: never
    on_success: always
    on_failure: always
